#' Determines whether lab data is EMRO or AFRO
#'
#' Outputs the name of the region which a country belongs to.
#'
#' @param country_name `str` Name of the country.
#'
#' @returns `str` A string, either `"EMRO"` or `"AFRO"`.
#' @examples
#' \dontrun{
#' get_region("algeria")
#' }
#'
#' @export
get_region <- function(country_name = Sys.getenv("DR_COUNTRY")) {
  # Format country_name
  country_name <- stringr::str_trim(stringr::str_to_upper(country_name))

  # Countries that belong in a region
  afro_ctry <- c(
    "ALGERIA", "ANGOLA", "BENIN", "BOTSWANA", "BURKINA FASO", "BURUNDI",
    "CABO VERDE", "CAMEROON", "CENTRAL AFRICAN REPUBLIC", "CHAD", "COMOROS",
    "CONGO", "COTE D IVOIRE", "COTE D'IVOIRE", "DEMOCRATIC REPUBLIC OF THE CONGO",
    "EQUATORIAL GUINEA", "ERITREA", "ESWATINI", "ETHIOPIA", "GABON", "GAMBIA",
    "GHANA", "GUINEA", "GUINEA-BISSAU", "KENYA", "LESOTHO", "LIBERIA", "MADAGASCAR",
    "MALAWI", "MALI", "MAURITANIA", "MAURITIUS", "MOZAMBIQUE", "NAMIBIA", "NIGER",
    "NIGERIA", "RWANDA", "SAO TOME AND PRINCIPE", "SENEGAL", "SEYCHELLES",
    "SIERRA LEONE", "SOUTH AFRICA", "SOUTH SUDAN", "TOGO", "UGANDA",
    "UNITED REPUBLIC OF TANZANIA", "WESTERN SAHARA", "ZAMBIA", "ZIMBABWE"
  )

  amro_ctry <- c(
    "ANGUILLA", "ANTIGUA AND BARBUDA", "ARGENTINA", "ARUBA", "BAHAMAS", "BARBADOS",
    "BELIZE", "BERMUDA", "BOLIVIA (PLURINATIONAL STATE OF)",
    "BONAIRE, SINT EUSTATIUS AND SABA", "BRAZIL", "BRITISH VIRGIN ISLANDS",
    "CANADA", "CAYMAN ISLANDS", "CHILE", "COLOMBIA", "COSTA RICA", "CUBA",
    "CURAÇAO", "DOMINICA", "DOMINICAN REPUBLIC", "ECUADOR", "EL SALVADOR",
    "FALKLAND ISLANDS (MALVINAS)", "FRENCH GUIANA", "GRENADA", "GUADELOUPE",
    "GUATEMALA", "GUYANA", "HAITI", "HONDURAS", "JAMAICA", "MARTINIQUE",
    "MEXICO", "MONTSERRAT", "NETHERLANDS ANTILLES", "NICARAGUA", "PANAMA",
    "PARAGUAY", "PERU", "PUERTO RICO", "SAINT BARTHÉLEMY", "SAINT KITTS AND NEVIS",
    "SAINT LUCIA", "SAINT MARTIN", "SAINT PIERRE AND MIQUELON",
    "SAINT VINCENT AND THE GRENADINES", "SINT MAARTEN", "SURINAME", "TRINIDAD AND TOBAGO",
    "TURKS AND CAICOS ISLANDS", "UNITED STATES OF AMERICA",
    "UNITED STATES VIRGIN ISLANDS", "URUGUAY", "VENEZUELA (BOLIVARIAN REPUBLIC OF)"
  )

  emro_ctry <- c(
    "AFGHANISTAN", "BAHRAIN", "DJIBOUTI", "EGYPT", "IRAN (ISLAMIC REPUBLIC OF)",
    "IRAQ", "JORDAN", "KUWAIT", "LEBANON", "LIBYA", "MOROCCO",
    "OCCUPIED PALESTINIAN TERRITORY, INCLUDING EAST JERUSALEM", "OMAN", "PAKISTAN",
    "QATAR", "SAUDI ARABIA", "SOMALIA", "SUDAN", "SYRIAN ARAB REPUBLIC", "TUNISIA",
    "UNITED ARAB EMIRATES", "YEMEN"
  )

  euro_ctry <- c(
    "ALBANIA", "ANDORRA", "ARMENIA", "AUSTRIA", "AZERBAIJAN", "BELARUS", "BELGIUM",
    "BOSNIA AND HERZEGOVINA", "BULGARIA", "CROATIA", "CYPRUS", "CZECHIA", "DENMARK",
    "ESTONIA", "FAROE ISLANDS", "FINLAND", "FRANCE", "GEORGIA", "GERMANY", "GIBRALTAR",
    "GREECE", "GREENLAND", "GUERNSEY", "HOLY SEE", "HUNGARY", "ICELAND", "IRELAND",
    "ISLE OF MAN", "ISRAEL", "ITALY", "JERSEY", "KAZAKHSTAN", "KOSOVO", "KYRGYZSTAN",
    "LATVIA", "LIECHTENSTEIN", "LITHUANIA", "LUXEMBOURG", "MALTA", "MAYOTTE", "MONACO",
    "MONTENEGRO", "NETHERLANDS", "NORTH MACEDONIA", "NORWAY", "POLAND", "PORTUGAL",
    "REPUBLIC OF MOLDOVA", "RÉUNION", "ROMANIA", "RUSSIAN FEDERATION", "SAINT HELENA",
    "SAN MARINO", "SERBIA", "SLOVAKIA", "SLOVENIA", "SPAIN", "SVALBARD AND JAN MAYEN ISLANDS",
    "SWEDEN", "SWITZERLAND", "TAJIKISTAN", "THE UNITED KINGDOM", "T\u00DCRKIYE",
    "TURKEY", "TURKMENISTAN", "UKRAINE", "UZBEKISTAN"
  )

  searo_ctry <- c(
    "BANGLADESH", "BHUTAN", "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA", "INDIA",
    "INDONESIA", "MALDIVES", "MYANMAR", "NEPAL", "SRI LANKA", "THAILAND", "TIMOR-LESTE"
  )

  wpro_ctry <- c(
    "AMERICAN SAMOA", "AUSTRALIA", "BRUNEI DARUSSALAM", "CAMBODIA", "CHINA",
    "CHRISTMAS ISLAND", "COCOS (KEELING) ISLANDS", "COOK ISLANDS", "FIJI",
    "FRENCH POLYNESIA", "GUAM", "JAPAN", "JOHNSTON ATOLL", "KIRIBATI",
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC", "MALAYSIA", "MARSHALL ISLANDS",
    "MICRONESIA (FEDERATED STATES OF)", "MIDWAY ISLANDS", "MONGOLIA", "NAURU",
    "NEW CALEDONIA", "NEW ZEALAND", "NIUE", "NORFOLK ISLAND",
    "NORTHERN MARIANA ISLANDS (COMMONWEALTH OF THE)", "PALAU", "PAPUA NEW GUINEA",
    "PHILIPPINES", "PITCAIRN ISLANDS", "REPUBLIC OF KOREA", "SAMOA", "SINGAPORE",
    "SOLOMON ISLANDS", "TOKELAU", "TONGA", "TUVALU", "VANUATU", "VIET NAM",
    "WAKE ISLAND", "WALLIS AND FUTUNA"
  )

  region <- dplyr::case_match(
    country_name,
    emro_ctry ~ "EMRO",
    afro_ctry ~ "AFRO",
    amro_ctry ~ "AMRO",
    euro_ctry ~ "EURO",
    wpro_ctry ~ "WPRO",
    searo_ctry ~ "SEARO",
    .default = NA
  )

  return(region)
}
